FROM python:2.7

RUN apt update -y && \
    apt install -y pandoc && \
    pip install twine pypandoc

WORKDIR /app

COPY . .

RUN make install-dev-deps && \
    make setup

ENTRYPOINT ["/bin/bash"]
